Repository effective-java-study-with-business/effective-java, pull requests merged in 2023-11, with the labels that each got.

#6 Item05 - 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라
  2장/자원을_직접_명시하지_말고_의존_객체_주입을_사용하라.md
Labels: 2장

#3 Item02 - 생성자에 매개변수가 많다면 빌더를 고려하라
  2장/Item02.md
Labels: 2장

#10 Item09 - try-finally보다는 try-with-resources를 사용하라
  3장/Item09 - try-finally보다는 try-with-resources를 사용하라.md
Labels: 2장

#2 item01-생성자대신정적팩토리메서드고려
  1장/item01-생성자대신정적팩토리메서드고려.md
  3장/equals를 재정의하려거든 hashCode도 재정의하라.md
Labels: 2장

#9 item11-equlas를재정의하려거든hashCode도재정의하라
  3장/item11.equlas를재정의하려거든hashCode도재정의하라.md
Labels: 3장

#7 Item12 - toString을 항상 재정의하자.
  .idea/libraries/commons_lang.xml
  .idea/uiDesigner.xml
  1장/img.png
  1장/toString을_항상_재정의하라.md
  effective-java.iml
  src/item12/Mock.java
  src/item12/User.java
Labels: 3장

#1 Item07 - 다 쓴 객체 참조는 해제하라
  .idea/libraries/commons_lang.xml
  .idea/uiDesigner.xml
  1장/img.png
  1장/toString을_항상_재정의하라.md
  1장/다_쓴_객체_참조는_해제하라.md
  effective-java.iml
  src/Main.java
  src/item07/Cache.java
  src/item07/Person.java
  src/item07/Stack.java
  src/item12/Mock.java
  src/item12/User.java
Labels: 2장

#5 Item03 - private 생성자나 열거 타입으로 싱글턴임을 보증하라
  2장/Item03-private_생성자나_열거_타입으로_싱글턴임을_보증하라.md
  src/item03/FooConnection.java
  src/item03/ReflectionAccessMain.java
  src/item03/factory/FooConnection.java
  src/item03/public_static/FooConnection.java
Labels: 2장

#8 Item06 - 불필요한 객체 생성을 피하라
  2장/item04 - 인스턴스화를 막으려거든 private 생성자를 사용하라.md
  2장/item06 - 불필요한 객체 생성을 피하라
  4장/Item15 - 클래스와 멤버의 접근 권한을 최소화하라
  src/item6/Adapter.java
  src/item6/AutoBoxing.java
Labels: 2장

#11 Item10 - equals는 일반 규약을 지켜 재정의 하라
  3장/Item10 - equals는 일반 규약을 지켜 재정의 하라.md
Labels: 3장

#13 item14 - Comparable을_구현할지_고려하라
  2장/item14-Comparable을_구현할지_고려하라.md
Labels: 4장

#16 item17-변경_가능성을_최소화하라
  2장/item09-try_finally보다는_try_with_resources를_사용하라.md
  4장/image/img.png
  4장/item17-변경_가능성을_최소화하라.md
Labels: 4장

#15 Item18-상속보다는_컴포지션을_사용하라
  4장/Item18-상속보다는_컴포지션을_사용하라.md
  src/item18/ForwardingSet.java
  src/item18/HashSetTest.java
  src/item18/InstrumentedHashSet.java
  src/item18/InstrumentedSet.java
Labels: 4장

#18 Item 19 - 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라
  2장/Item09-try_finally보다는_try_with_resources를_사용하라.md
  4장/README.md
  4장/item15-클래스와_멤버의_접근_권한을_최소화하라.md
  4장/item19-상속을_고려해_설계하고_문서화하라_그러지_않았다면_상속을_금지하라.md
Labels: 4장

#12 itme16-public클래스에서는public필드가아닌접근자메서드를사용하라
  4장/itme16-public클래스에서는public필드가아닌접근자메서드를사용하라.md
Labels: 4장
