Repository effective-java-study-with-business/effective-java, pull requests merged in 2024-03, with the labels that each got.

#71 item75-예외의_상세_메시지에_실패_관련_정보를_담으라.md
  10장/item75-예외의_상세_메시지에_실패_관련_정보를_담으라.md
Labels: 10장

#69 Item65 - 리플렉션보다는 인터페이스를 사용하라
  9장/item65-리플렉션보다는_인터페이스를_사용하라.md
  src/item65/Animal.java
  src/item65/Cat.java
  src/item65/Eating.java
  src/item65/Person.java
  src/item65/ReflectionMain01.java
  src/item65/ReflectionMain02.java
  src/item65/Test01.java
Labels: 10장

#74 Item80-스레드보다는 실행자,태스크,스트림을 애용하라.
  11장/img.png
  11장/img_1.png
  11장/img_2.png
  11장/img_3.png
  11장/img_4.png
  11장/img_5.png
  11장/img_6.png
  11장/img_7.png
  11장/img_8.png
  11장/item80-스레드보다는_실행자,태스크,스트림을_애용하라.md
  src/item46/StreamCount.java
  src/item80/ExecutorFramework.java
Labels: 11장

#77 item81-wait와_notify보다는_동시성_유틸리티를_애용하라.
  11장/item81-wait와_notify보다는_동시성_유틸리티를_애용하라.md
  src/item81/CountDowLatchTest.java
Labels: 11장

#73 Item74 - 메서드가 던지는 모든 예외를 문서화해라
  10장/item-75-메서드가_던지는_모든_예외를_문서화하라.md
  src/item74/Test.java
Labels: 10장

#72 item78-공유중인_가변_데이터는_동기화해_사용하라
  11장/item78-공유중인_가변_데이터는_동기화해_사용하라.md
  src/item78/StopThread.java
Labels: 11장

#56 item45 - 스트림은 주의해서 사용하라
  7장/item45-스트림은_주의해서_사용하라.md
  7장/item45/img.png
  src/item45/Applicant.java
  src/item45/ApplicantServiceImpl.java
  src/item45/BlindInterviewee.java
  src/item45/Career.java
  src/item45/StreamDebug.java
Labels: 7장

#76 item87-커스텀_직렬화_형태를_고민해봐라.md
  12장/item87-커스텀_직렬화_형태를_고민해봐라.md
Labels: 12장

#80 item 85 - 자바 직렬화의 대안을 찾으라
  12장/item85-자바_직렬화의_대안을_찾으라.md
Labels: 12장
