Repository effective-java-study-with-business/effective-java, pull requests merged in 2024-01, with the labels that each got.

#40 Item40-@Override_애너테이션을_일관되게_사용하라
  6장/ item40-@Override_애너테이션을_일관되게_사용하라.md
Labels: 6장

#31 Item37-ordinal_인덱싱_대신_EnumMap을_사용하라
  .idea/misc.xml
  6장/item37-ordinal_인덱싱_대신_EnumMap을_사용하라.md
  src/item37/EnumMapTest.java
  src/item37/MultiEnumMapTest.java
  src/item37/Phase.java
  src/item37/Plant.java
Labels: 6장

#41 item39-명명 패턴보다 애너테이션을 사용하라
  6장/image/img.png
  6장/image/img_1.png
  6장/image/img_2.png
  6장/image/img_3.png
  6장/image/img_4.png
  6장/item39-명명_패턴보단_애너테이션을_사용하라.md
Labels: 6장

#38 item42-익명 클래스보다는 람다를 사용하라
  7장/item42-익명_클래스보다는_람다를_사용하라.md
Labels: 7장

#37 item38-확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라.md
  6장/item38-확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라.md
Labels: 6장

#39 Item32 제네릭과 가변인수를 함께 쓸 때는 신중하라
  5장/README.md
  5장/image/item32_0.png
  5장/image/item32_1.png
  5장/image/item32_2.png
  5장/item29-이왕이면제네릭타입으로만들라.md
  5장/item31-한정적_와일드카드를_사용해_API_유연성을_높이라.md
  5장/item32-제네릭과_가변인수를_함께_쓸_때는_신중하라.md
  5장/item33-타입_안전_이종_컨테이너를_고려하라.md
  effective-java.iml
  src/item32/ItemTest.java
Labels: 5장

#44 item46-스트림에서는 부작용 없는 함수를 사용하라
  7장/item46-스트림에서는_부작용_없는_함수를_사용하라.md
  src/item46/Album.java
  src/item46/Artist.java
  src/item46/StreamCount.java
Labels: 7장

#49 item 55 - 옵셔널 반환은 신중히 하라
  8장/item55-옵셔널_반환은_신중히_하라.md
Labels: 8장

#43 item50-적시에 방어적 복사본을 만들라.
  8장/item50-적시에_방어적_복사본을_만들라.md
Labels: 8장

#50 item 51 - 메서드 시그니처를 신중히 설계하라
  8장/item51-메서드_시그니처를_신중히_설계하라.md
  src/item51/Astronomy.java
  src/item51/AstronomyMain.java
  src/item51/CardGame.java
  src/item51/CardGameMain.java
  src/item51/SubListIndexMain.java
Labels: 8장

#48 item 48 - 스트림 병렬화는 주의해서 적용하라
  7장/item48-스트림_병렬화는_주의해서_적용하라
Labels: 7장

#42 item49-매개변수가유효한지검사하라
  8장/item49-매개변수가유효한지검사하라.md
Labels: 8장

#54 Item53 - 가변인수는 신중히 사용하자
  8장/README.md
  8장/image/img.png
  8장/image/img_1.png
  8장/image/img_2.png
  8장/item53-가변인수는_신중히_사용하자.md
  src/item53/Varargs.java
Labels: 8장

#53 item 47 - 반환 타입으로는 스트림보다 컬렉션이 낫다
  7장/images/불편.png
  7장/images/편안.png
  7장/item47-반환_타입으로는_스트림보다_컬렉션이_낫다.md
Labels: 7장

#47 item36-비트_필드_대신_EnumSet을_사용하라
  6장/item36-비트_필드_대신_EnumSet을_사용하라.md
  src/item36/Arrow.java
  src/item36/Arrow2.java
  src/item36/BitFieldTest.java
  src/item36/EnumSetTest.java
Labels: 6장

#55 item54 - null이 아닌, 빈 컬렉션이나 배열을 반환하라
  8장/item54-null이_아닌_빈_컬렉션이나_배열을_반환하라.md
Labels: 8장

#58 item60-정확한_답이_필요하다면_float와_double은_피하라
  9장/item60-정확한_답이_필요하다면_float와_double은_피하라.md
Labels: 9장
