Repository effective-java-study-with-business/effective-java, pull requests merged in 2024-02, with the labels that each got.

#61 item-52_다중_정의는_신중히_사용하라
  8장/item-52_다중_정의는_신중히_사용하라.md
Labels: 8장

#62 item62-다른_타입이_적절하다면_문자열_사용을_피하라
  9장/item62-다른_타입이_적절하다면_문자열_사용을_피하라.md
Labels: 9장

#59 item61-박싱된_기본_타입보다는_기본_타입을_사용하라
  10장/item71-필요_없는_검사_예외_사용은_피하라.md
  9장/item61-박싱된_기본_타입보다는_기본_타입을_사용하라.md
Labels: 9장

#67 item66-네이티브_메서드는_신중히_사용하라.md
  9장/item66-네이티브_메서드는_신중히_사용하라.md
Labels: 9장

#68 item69-예외는_진짜_예외_상황에만_사용하라
  10장/item69-예외는_진짜_예외_상황에만_사용하라.md
  src/item69/Bird.java
  src/item69/Comparison.java
Labels: 10장

#57 item63 - 문자열 연결은 느리니 주의하라
  9장/item63-문자열_연결은_느리니_주의하라.md
Labels: 9장

#65 item70 - 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라
  10장/item70-복구할_수_있는_상황에는_검사_예외를,_프로그래밍_오류에는_런타임_예외를_사용하라.md
Labels: 10장

#75 Item83-지연 초기화는 신중히 사용하라
  11장/item83-지연_초기화는_신중히_사용하라.md
Labels: 11장

#66 item64-객체는_인터페이스를_사용해_참조하라
  9장/item64-객체는_인터페이스를_사용해_참조하라.md
Labels: 9장

#60 item58 - 전통적인 for문보다는 for-each문을 사용하라
  9장/item58-전통적인_for문보다는_for-each문을_사용하라.md
  src/item58/ForEachExample.java
Labels: 9장
